Repository aviator-co/av, pull requests merged in 2022-07, with the labels that each got.

#39 [MER-873] Highlight current branch in the stack
  cmd/av/stack_tree.go
Labels: mergequeue

#38 Fetch PR info from GH before trying to open it
  internal/actions/pr.go
  internal/gh/client.go
  internal/gh/common.go
  internal/gh/pullrequest.go
Labels: avbeta-stackedprs

#41 [MER-877] cli: improve error message if stack branch fails
  cmd/av/stack_branch.go
  internal/git/git.go
Labels: mergequeue

#45 [MER-1006] added stack prev and next commands
  cmd/av/stack_next.go
  cmd/av/stack_prev.go
Labels: mergequeue, avbeta-stackedprs

#46 Fixed newlines on returns
  cmd/av/stack_next.go
  cmd/av/stack_prev.go
Labels: mergequeue

#47 fix(stack sync): Handle stack sync rebase for >= 3 branches correctly
  cmd/av/stack_branch.go
  cmd/av/stack_sync.go
  cmd/av/stack_tree.go
  e2e_tests/av.go
  e2e_tests/stack_reparent_test.go
  e2e_tests/stack_sync_test.go
  internal/actions/pr.go
  internal/actions/reparent.go
  internal/git/git.go
  internal/git/gittest/commit.go
  internal/git/rebase.go
  internal/git/revlist.go
  internal/meta/branch.go
  internal/meta/branchstate.go
  internal/stacks/metadata.go
  internal/stacks/sync.go
Labels: mergequeue, avbeta-stackedprs

#48 fix(stack-sync): cleanup rebase state on sync --abort
  cmd/av/stack_sync.go
  e2e_tests/av.go
  e2e_tests/stack_sync_test.go
  internal/git/rebase.go
Labels: avbeta-stackedprs
