Repository aviator-co/av, pull requests merged in 2022-06, with the labels that each got.

#24 Update go.yml
  .github/workflows/go.yml
Labels: mergequeue

#23 [MER-848] Add automatic version check
  .goreleaser.yaml
  cmd/av/main.go
  go.mod
  go.sum
  internal/config/config.go
  internal/config/version.go
Labels: mqbeta-stackedprs

#27 [MER-867] Add default PR title from commit subject
  cmd/av/helpers.go
  cmd/av/init.go
  cmd/av/pr.go
  internal/actions/pr.go
  internal/git/show.go
  internal/meta/repository.go
Labels: mergequeue

#26 [MER-866] Implement av fetch command
  cmd/av/fetch.go
  cmd/av/main.go
  internal/gh/client.go
  internal/gh/pullrequest.go
Labels: mergequeue

#25 Implement av stack reparent command
  cmd/av/stack.go
  cmd/av/stack_reparent.go
  cmd/av/stack_sync.go
  e2e_tests/av.go
  e2e_tests/stack_reparent_test.go
  go.mod
  go.sum
  internal/git/gittest/repo.go
  internal/meta/branch.go
  internal/utils/sliceutils/sliceutils.go
Labels: mergequeue

#28 [MER-870] Fix bug in av pr create if commit only has headline (no body)
  internal/actions/pr.go
  internal/git/git.go
  internal/git/show.go
  internal/meta/branch.go
Labels: mergequeue

#29 [MER-871] Improve upgrade message formatting, fix v prefix issue in released version
  .goreleaser.yaml
  cmd/av/main.go
Labels: mergequeue

#31 [MER-875] Implement pushing branch during stack sync
  cmd/av/fetch.go
  cmd/av/main.go
  cmd/av/stack_sync.go
  e2e_tests/stack_sync_test.go
  internal/actions/pr.go
  internal/actions/push.go
  internal/utils/colors/colorutils.go
Labels: mergequeue

#32 [MER-882] Handle --abort/--continue'd rebase during stack sync
  cmd/av/stack_sync.go
  internal/actions/pr.go
  internal/stacks/sync.go
  internal/utils/stringutils/removelines.go
  internal/utils/stringutils/removelines_test.go
Labels: mergequeue

#36 [MER-927] auto open browser config
  .gitignore
  cmd/av/fetch.go
  cmd/av/init.go
  cmd/av/main.go
  cmd/av/pr.go
  internal/actions/pr.go
  internal/config/config.go
  internal/utils/browser/browser.go
Labels: avbeta-stackedprs

#37 Add ability to create draft PRs with av pr create
  cmd/av/pr.go
  internal/actions/pr.go
  internal/config/config.go
Labels: mergequeue, avbeta-stackedprs
